spring:
  application:
    name: monitoring-prometheus-grafana

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags: 
      application: ${spring.application.name}
